### ISSUE TITLE
Leetcode 841. Keys and Rooms

### ISSUE THREAD

**Issue by Wizmann** [LuolinRowling/Algorithms#5]
现在有N个房间，编号为[0 ... N - 1]。每一个房间里都有若干把钥匙（也可能没有钥匙）。

房间0的门是打开的，问在给定的情形下，你能不能把所有房间的门都打开。

输入的是一个列表rooms，rooms[i]是一个整数数组（可能为空），rooms[i][j]代表"房间i"里有"房间rooms[i][j]"的钥匙。

样例1：
```
Input: [[1],[2],[3],[]]
Output: true
```

先从房间0拿到房间1的钥匙，然后打开房间1的门，从里面拿到房间2的钥匙。。。直到把所有的门都打开。

样例2：
```
Input: [[1,3],[3,0,1],[2],[0]]
Output: false
```

无论用什么方法，我们都无法进入房间2。

URL: https://leetcode.com/problems/keys-and-rooms/description/

**Comment by Wizmann** [comment]
Tags:
拓扑排序

**Comment by LuolinRowling** [comment]
/**
 * @param {number[][]} rooms
 * @return {boolean}
 */
var canVisitAllRooms = function(rooms) {
    var s = [0],
        r = [];
    
    while(s.length > 0) {
        var cur = s.shift();
        
        if (r.indexOf(cur) != -1)
            continue;
        else {
            r.push(cur);
            for (var i = 0; i < rooms[cur].length; i++) {
                s.push(rooms[cur][i]);
            }
        }
    }
    
    if (r.length == rooms.length) return true;
    else return false;
};

**Comment by LuolinRowling** [comment]
`/**
 * @param {number[][]} rooms
 * @return {boolean}
 */
var canVisitAllRooms = function(rooms) {
    var s = [0],
        r = [];
    
    while(s.length > 0) {
        var cur = s.shift();
        
        if (r.indexOf(cur) != -1)
            continue;
        else {
            r.push(cur);
            for (var i = 0; i < rooms[cur].length; i++) {
                s.push(rooms[cur][i]);
            }
        }
    }
    
    if (r.length == rooms.length) return true;
    else return false;
};`

**Comment by LuolinRowling** [comment]
```javascript
/**
 * @param {number[][]} rooms
 * @return {boolean}
 */
var canVisitAllRooms = function(rooms) {
    var s = [0],
        r = [];
    
    while(s.length > 0) {
        var cur = s.shift();
        
        if (r.indexOf(cur) != -1)
            continue;
        else {
            r.push(cur);
            for (var i = 0; i < rooms[cur].length; i++) {
                s.push(rooms[cur][i]);
            }
        }
    }
    
    if (r.length == rooms.length) return true;
    else return false;
};
```

**Comment by LuolinRowling** [comment]
```javascript
/**
 * @param {number[][]} rooms
 * @return {boolean}
 */
var canVisitAllRooms = function(rooms) {
    var p = [0],
        v = [];
    var len = rooms.length;
    
    for (var i = 1; i < len; i++) {
        p.push(Number.POSITIVE_INFINITY);
    }
    
    
    while(len > 0) {
        var pos = findMin(v, p);
        if (pos == -1) return false;
        v[pos] = 1;
        
        for (var i = 0; i < rooms[pos].length; i++) {
            var target = rooms[pos][i];
            p[target] = Math.min(p[target], p[pos] + 1);
        }
        len--;
    }
    
    for (var i = 0; i < p.length; i++) {
        if (p[i] == Number.POSITIVE_INFINITY) return false;
    }
    
    return true;
    
};

function findMin(v, p) {
    var minIndex = -1,
        min = Number.POSITIVE_INFINITY;
    
    for (var i = 0; i < p.length; i++) {
        if (v[i] == 1) continue;
        if (p[i] < min) {
            minIndex = i;
            min = p[i];
        }
    }
    
    return minIndex;
}
```
